// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfz0ehLNNHonUJGlxzEjvyLCb2rYgkK1U',
    appId: '1:652467266819:web:be189eb9dd8cabe5c2f536',
    messagingSenderId: '652467266819',
    projectId: 'campus-pulse-a9f21',
    authDomain: 'campus-pulse-a9f21.firebaseapp.com',
    databaseURL: 'https://campus-pulse-a9f21-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-pulse-a9f21.firebasestorage.app',
    measurementId: 'G-5SHPWD86HV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ocL3vUUgEvqD99cBZjEncpXVUKAhDGc',
    appId: '1:652467266819:android:ef4772867769a8b6c2f536',
    messagingSenderId: '652467266819',
    projectId: 'campus-pulse-a9f21',
    databaseURL: 'https://campus-pulse-a9f21-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-pulse-a9f21.firebasestorage.app',
  );
}
